-
  id: 1
  poem:
    kanji: 秋の田の かりほの庵の 苫をあらみ わが衣手は 露にぬれつつ
    kana: あきのたのかりほのいほのとまをあらみ　わがころもではつゆにぬれつつ
    en:    Coarse the rush-mat roof Sheltering the harvest-hut Of the autumn rice-field;  And my sleeves are growing wet With the moisture dripping through.
  comment: 「刈穂の庵」は、秋の収穫時に田に作られる仮小屋。獣に稲が荒らされないように泊まりこみで番をしたりする。蓆(むしろ)で編んだその屋根が粗いので、衣の袖が徐々に濡れていってしまうという歌。秋の静かな長夜の雰囲気が伝わってくる。
  poet:
    name:
      ja: 天智天皇
      en:    Emperor Tenchi
    sex: 1
    monk: 0
    period: 626-672
    info: 中臣鎌足らと蘇我入鹿暗殺を行い、大化の改新をおこした中大兄皇子のこと。朝鮮半島で行われた白村江の戦いで唐・新羅連合に大敗したのち、天智天皇として即位した。歌人としては、百人一首の第一首を飾るほか万葉集にも4首が選出されている。

-
  id: 2
  poem:
    kanji: 春過ぎて 夏来にけらし 白妙の 衣干すてふ 天の香具山
    kana: はるすぎてなつきにけらししろたへの　ころもほすてふあまのかぐやま
    en:   The spring has passed And the summer come again; For the silk-white robes,  So they say, are spread to dry On the "Mount of Heaven's Perfume".
  comment: いつの間にか春が過ぎて夏が来ていたのですね。夏になると白い衣を干すという天の香具山に、あのように衣が干されているのですから。初夏の青空のもと、山に白い衣がたなびく様子が目に浮かぶ、爽やかで叙景的な歌。
  poet:
    name:
      ja: 持統天皇
      en:    Empress Jitō
    sex: 2
    monk: 0
    period: 645-703
    info: 天智天皇の娘。叔父の大海人皇子（天武天皇）に嫁ぐ。天智天皇の死後、天武天皇とともに壬申の乱を起こし皇后となる。天武天皇没後、持統天皇として即位。その後存命中に太子に皇位を委譲した。
